// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserToken() {
  return window['go']['services']['AuthService']['GetUserToken']();
}

export function Login() {
  return window['go']['services']['AuthService']['Login']();
}

export function Logout() {
  return window['go']['services']['AuthService']['Logout']();
}

export function Start(arg1) {
  return window['go']['services']['AuthService']['Start'](arg1);
}
