// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {core} from '../models';
import {config} from '../models';

export function GetUserToken():Promise<string>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function Start(arg1:context.Context,arg2:core.GrpcV1Client,arg3:config.Config):Promise<void>;
