// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetUserToken():Promise<string>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function Start(arg1:context.Context):Promise<void>;
