// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function DeleteCopy(arg1:number):Promise<void>;

export function DeleteDownload(arg1:number):Promise<void>;

export function DeleteUpload(arg1:number):Promise<void>;

export function GetCopyList():Promise<Array<models.Copy>>;

export function GetDownloadList():Promise<Array<models.Download>>;

export function GetUploadList():Promise<Array<models.Upload>>;

export function Start(arg1:context.Context):Promise<void>;
