// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTransportManager(arg1) {
  return window['go']['services']['DatabaseService']['DeleteTransportManager'](arg1);
}

export function DeleteTransportManagerByType(arg1) {
  return window['go']['services']['DatabaseService']['DeleteTransportManagerByType'](arg1);
}

export function GetTransportManagers(arg1) {
  return window['go']['services']['DatabaseService']['GetTransportManagers'](arg1);
}

export function Start(arg1) {
  return window['go']['services']['DatabaseService']['Start'](arg1);
}
