// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function DeleteTransportManager(arg1:number):Promise<void>;

export function DeleteTransportManagerByType(arg1:string):Promise<void>;

export function GetTransportManagers(arg1:string):Promise<Array<services.TransportManager>>;

export function Start(arg1:context.Context):Promise<void>;
