// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCopy(arg1) {
  return window['go']['services']['DatabaseService']['DeleteCopy'](arg1);
}

export function DeleteDownload(arg1) {
  return window['go']['services']['DatabaseService']['DeleteDownload'](arg1);
}

export function DeleteUpload(arg1) {
  return window['go']['services']['DatabaseService']['DeleteUpload'](arg1);
}

export function GetCopyList() {
  return window['go']['services']['DatabaseService']['GetCopyList']();
}

export function GetDownloadList() {
  return window['go']['services']['DatabaseService']['GetDownloadList']();
}

export function GetUploadList() {
  return window['go']['services']['DatabaseService']['GetUploadList']();
}

export function Start(arg1) {
  return window['go']['services']['DatabaseService']['Start'](arg1);
}
