// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFile(arg1, arg2) {
  return window['go']['services']['FileService']['CopyFile'](arg1, arg2);
}

export function DownloadFile(arg1) {
  return window['go']['services']['FileService']['DownloadFile'](arg1);
}

export function GetFileList(arg1) {
  return window['go']['services']['FileService']['GetFileList'](arg1);
}

export function Mkdir(arg1) {
  return window['go']['services']['FileService']['Mkdir'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['services']['FileService']['MoveFile'](arg1, arg2);
}

export function PlayVideo(arg1) {
  return window['go']['services']['FileService']['PlayVideo'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['services']['FileService']['RemoveFile'](arg1);
}

export function Start(arg1, arg2, arg3) {
  return window['go']['services']['FileService']['Start'](arg1, arg2, arg3);
}

export function UploadFile(arg1) {
  return window['go']['services']['FileService']['UploadFile'](arg1);
}
