// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFileSync(arg1) {
  return window['go']['services']['FileSyncService']['AddFileSync'](arg1);
}

export function GetFileSyncList() {
  return window['go']['services']['FileSyncService']['GetFileSyncList']();
}

export function RemoveFileSync(arg1) {
  return window['go']['services']['FileSyncService']['RemoveFileSync'](arg1);
}

export function StartFileSync(arg1) {
  return window['go']['services']['FileSyncService']['StartFileSync'](arg1);
}

export function StopFileSync(arg1) {
  return window['go']['services']['FileSyncService']['StopFileSync'](arg1);
}
