// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';

export function AddFileSync(arg1:v1.Sync):Promise<v1.Sync>;

export function GetFileSyncList():Promise<Array<v1.Sync>>;

export function RemoveFileSync(arg1:string):Promise<void>;

export function StartFileSync(arg1:v1.Sync):Promise<void>;

export function StopFileSync(arg1:v1.Sync):Promise<void>;
