// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DelLocalStorage(arg1:string):Promise<void>;

export function GetLocalStorage(arg1:string):Promise<any>;

export function SetLocalStorage(arg1:string,arg2:any):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;
