// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';
import {context} from '../models';
import {core} from '../models';

export function AddLocation(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<v1.AddLocationResponse>;

export function GetLocations():Promise<Array<v1.Location>>;

export function RemoveLocation(arg1:string):Promise<v1.RemoveLocationResponse>;

export function Start(arg1:context.Context,arg2:core.GrpcV1Client):Promise<void>;
