// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DelLocalStorage(arg1) {
  return window['go']['services']['LocalStorageService']['DelLocalStorage'](arg1);
}

export function GetLocalStorage(arg1) {
  return window['go']['services']['LocalStorageService']['GetLocalStorage'](arg1);
}

export function SetLocalStorage(arg1, arg2) {
  return window['go']['services']['LocalStorageService']['SetLocalStorage'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['services']['LocalStorageService']['Start'](arg1);
}
