// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['LocationService']['AddLocation'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLocations() {
  return window['go']['services']['LocationService']['GetLocations']();
}

export function RemoveLocation(arg1) {
  return window['go']['services']['LocationService']['RemoveLocation'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['services']['LocationService']['Start'](arg1, arg2);
}
