// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';

export function GetNodes():Promise<Array<v1.Node>>;

export function RemoveNode(arg1:string):Promise<void>;
