// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNodes() {
  return window['go']['services']['NodeService']['GetNodes']();
}

export function RemoveNode(arg1) {
  return window['go']['services']['NodeService']['RemoveNode'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['services']['NodeService']['Start'](arg1, arg2);
}
