// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDownloadPath():Promise<string>;

export function GetDownloadThreads():Promise<number>;

export function SetDownloadPath(arg1:string):Promise<void>;

export function SetDownloadThreads(arg1:number):Promise<void>;
