// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLog() {
  return window['go']['services']['PreferencesService']['ClearLog']();
}

export function GetDownloadPath() {
  return window['go']['services']['PreferencesService']['GetDownloadPath']();
}

export function GetDownloadThreads() {
  return window['go']['services']['PreferencesService']['GetDownloadThreads']();
}

export function ReadLog(arg1) {
  return window['go']['services']['PreferencesService']['ReadLog'](arg1);
}

export function SetDownloadPath(arg1) {
  return window['go']['services']['PreferencesService']['SetDownloadPath'](arg1);
}

export function SetDownloadThreads(arg1) {
  return window['go']['services']['PreferencesService']['SetDownloadThreads'](arg1);
}
