// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddS3Storage(arg1, arg2, arg3) {
  return window['go']['services']['StorageService']['AddS3Storage'](arg1, arg2, arg3);
}

export function AddStorageLink(arg1) {
  return window['go']['services']['StorageService']['AddStorageLink'](arg1);
}

export function CleanStorageLink(arg1) {
  return window['go']['services']['StorageService']['CleanStorageLink'](arg1);
}

export function GetStorageLinks() {
  return window['go']['services']['StorageService']['GetStorageLinks']();
}

export function GetStorages() {
  return window['go']['services']['StorageService']['GetStorages']();
}

export function RemoveStorage(arg1) {
  return window['go']['services']['StorageService']['RemoveStorage'](arg1);
}

export function RemoveStorageLink(arg1) {
  return window['go']['services']['StorageService']['RemoveStorageLink'](arg1);
}
