// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';
import {context} from '../models';
import {core} from '../models';

export function AddS3Storage(arg1:string,arg2:v1.StorageS3Config,arg3:v1.StorageNetwork):Promise<v1.AddStorageResponse>;

export function AddStorageLink(arg1:v1.StorageLink):Promise<v1.AddStorageLinkResponse>;

export function CleanStorageLink(arg1:string):Promise<void>;

export function GetStorageLinks():Promise<Array<v1.StorageLink>>;

export function GetStorages():Promise<Array<v1.Storage>>;

export function RemoveStorage(arg1:string):Promise<void>;

export function RemoveStorageLink(arg1:string):Promise<void>;

export function Start(arg1:context.Context,arg2:core.GrpcV1Client):Promise<void>;
