// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatBytes(arg1) {
  return window['go']['services']['SystemService']['FormatBytes'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['services']['SystemService']['OpenFile'](arg1);
}

export function ParseBytes(arg1) {
  return window['go']['services']['SystemService']['ParseBytes'](arg1);
}

export function SelectDirectoryDialog(arg1) {
  return window['go']['services']['SystemService']['SelectDirectoryDialog'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['services']['SystemService']['Start'](arg1, arg2);
}

export function StartWebsocketClient() {
  return window['go']['services']['SystemService']['StartWebsocketClient']();
}

export function Stop() {
  return window['go']['services']['SystemService']['Stop']();
}

export function StopWebsocketClient() {
  return window['go']['services']['SystemService']['StopWebsocketClient']();
}
