// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {config} from '../models';

export function FormatBytes(arg1:number):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function ParseBytes(arg1:string):Promise<number>;

export function SelectDirectoryDialog(arg1:string):Promise<string>;

export function Start(arg1:context.Context,arg2:config.Config):Promise<void>;

export function StartWebsocketClient():Promise<void>;

export function Stop():Promise<void>;
