// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';
import {context} from '../models';
import {core} from '../models';

export function GetUserInfo():Promise<v1.GetUserInfoResponse>;

export function Start(arg1:context.Context,arg2:core.GrpcV1Client):Promise<void>;
