// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserInfo() {
  return window['go']['services']['UserService']['GetUserInfo']();
}

export function Start(arg1, arg2) {
  return window['go']['services']['UserService']['Start'](arg1, arg2);
}
