// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function GetUserToken(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1418821304) as any;
    return $resultPromise;
}

export function Login(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2243121105) as any;
    return $resultPromise;
}

export function Logout(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2460922482) as any;
    return $resultPromise;
}
