// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteTransportManager(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3723533392, id) as any;
    return $resultPromise;
}

export function DeleteTransportManagerByType(typ: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3495072053, typ) as any;
    return $resultPromise;
}

export function GetTransportManagers(typ: string): Promise<($models.TransportManager | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(53090802, typ) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.TransportManager.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
