// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../pixelfs/gen/pixelfs/v1/models.js";

export function AddFileSync(sync: v1$0.Sync | null): Promise<v1$0.Sync | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3146694379, sync) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetFileSyncList(): Promise<(v1$0.Sync | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1935857332) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function RemoveFileSync(syncId: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3807705166, syncId) as any;
    return $resultPromise;
}

export function StartFileSync(sync: v1$0.Sync | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2684891168, sync) as any;
    return $resultPromise;
}

export function StopFileSync(sync: v1$0.Sync | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(427819498, sync) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = v1$0.Sync.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
