// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../pixelfs/gen/pixelfs/v1/models.js";

export function AddLocation(nodeId: string, name: string, path: string, blockSize: string, blockDuration: number): Promise<v1$0.AddLocationResponse | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4083341455, nodeId, name, path, blockSize, blockDuration) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetLocations(): Promise<(v1$0.Location | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1361061013) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function RemoveLocation(locationId: string): Promise<v1$0.RemoveLocationResponse | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4217976010, locationId) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = v1$0.AddLocationResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = v1$0.Location.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = v1$0.RemoveLocationResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
