// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function DelLocalStorage(path: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4221340279, path) as any;
    return $resultPromise;
}

export function GetLocalStorage(path: string): Promise<any> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2438219278, path) as any;
    return $resultPromise;
}

export function SetLocalStorage(path: string, value: any): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1551914602, path, value) as any;
    return $resultPromise;
}
