// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function GetDownloadPath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2651122025) as any;
    return $resultPromise;
}

export function GetDownloadThreads(): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(261397623) as any;
    return $resultPromise;
}

export function SetDownloadPath(path: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2750893029, path) as any;
    return $resultPromise;
}

export function SetDownloadThreads(threads: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(716075531, threads) as any;
    return $resultPromise;
}
