// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function ClearLog(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(71500246) as any;
    return $resultPromise;
}

export function OpenFile(filePath: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1251566617, filePath) as any;
    return $resultPromise;
}

export function ReadLog(reverse: boolean): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1822017759, reverse) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SelectDirectoryDialog(title: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(683942154, title) as any;
    return $resultPromise;
}

export function StartWebsocketClient(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(821161219) as any;
    return $resultPromise;
}

export function StopWebsocketClient(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3051901481) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
