// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function FormatBytes(bytes: number): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3491705696, bytes) as any;
    return $resultPromise;
}

export function ParseBytes(str: string): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2840935004, str) as any;
    return $resultPromise;
}
